version: 2.1

description: >
  Terragrunt run-all plan with drift email via SES.
  Includes SOPS, CircleCI IP ranges, and flexible exclude-dir handling.

orbs:
  aws-cli: circleci/aws-cli@5.4.0

executors:
  terragrunt:
    parameters:
      image:
        type: string
        default: "alpine/terragrunt:1.12.2"
    docker:
      - image: << parameters.image >>

commands:
  install-sops:
    description: "Install SOPS"
    parameters:
      version:
        type: string
        default: "v3.10.2"
    steps:
      - run:
          name: Install SOPS (<< parameters.version >>)
          command: |
            set -e
            apk add --no-cache curl
            curl -sSLo /usr/local/bin/sops \
              https://github.com/getsops/sops/releases/download/<< parameters.version >>/sops-<< parameters.version >>.linux.amd64
            chmod +x /usr/local/bin/sops

  install-misc:
    description: "Install misc deps (bind-tools, jq)"
    steps:
      - run:
          name: Install miscellaneous dependencies
          command: |
            set -e
            apk add --no-cache bind-tools jq

jobs:
  drift-detection:
    description: "Run terragrunt run-all plan and send SES email on drift/failure"
    circleci_ip_ranges: true
    parameters:
      # Infra location
      region:
        type: string
      account_type:
        type: string
      environment:
        type: string
      account_id:
        type: string
      deployments_root:
        type: string
        default: "deployments"
      role_name:
        type: string
      terragrunt_image:
        type: string
        default: "alpine/terragrunt:1.12.2"
      tg_queue_exclude_dirs:
        description: "Comma-separated list of dirs to exclude from run-all"
        type: string
        default: ""
      # Email / SES
      drift_email_to:
        type: string
      drift_email_from:
        type: string
      drift_email_from_name:
        type: string
        default: "Terraform Drift Detection"
      ses_region:
        type: string
      dry_run:
        type: boolean
        default: true

    executor:
      name: terragrunt
      image: << parameters.terragrunt_image >>

    steps:
      - checkout

      - aws-cli/setup:
          role_arn: arn:aws:iam::<< parameters.account_id >>:role/<< parameters.role_name >>
          region: << parameters.region >>

      - install-sops
      - install-misc
      
      - run:
          name: Dry run print all inputs
          command: |
            echo "drift-detection inputs:"
            echo "  region:                << parameters.region >>"
            echo "  account_type:          << parameters.account_type >>"
            echo "  environment:           << parameters.environment >>"
            echo "  account_id:            << parameters.account_id >>"
            echo "  deployments_root:      << parameters.deployments_root >>"
            echo "  role_name:             << parameters.role_name >>"
            echo "  terragrunt_image:      << parameters.terragrunt_image >>"
            echo "  tg_queue_exclude_dirs: << parameters.tg_queue_exclude_dirs >>"
            echo "  drift_email_to:        << parameters.drift_email_to >>"
            echo "  drift_email_from:      << parameters.drift_email_from >>"
            echo "  drift_email_from_name: << parameters.drift_email_from_name >>"
            echo "  ses_region:            << parameters.ses_region >>"
            echo "  dry_run:               << parameters.dry_run >>"
            # (Optional) show whether SES creds are present without leaking them
            if [ -n "${SES_LOGIN:-}" ]; then echo "  SES_LOGIN:             [set]"; else echo "  SES_LOGIN:             [unset]"; fi

      - run:
          name: Dry run gate
          command: |
            if [ "<< parameters.dry_run >>" = "true" ]; then
              echo "Dry run enabled; stopping before Terragrunt/SES steps."
              exit 0
            fi
