#!/bin/bash
# Build script to generate write_validate_drift.sh from validate_drift.py
# This maintains a single source of truth while keeping the orb packable.
#
# Usage: ./scripts/generate_python_wrapper.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

PYTHON_SOURCE="${PROJECT_ROOT}/src/scripts/validate_drift.py"
SHELL_WRAPPER="${PROJECT_ROOT}/src/scripts/write_validate_drift.sh"

echo "Generating shell wrapper from Python source..."
echo "  Source: ${PYTHON_SOURCE}"
echo "  Target: ${SHELL_WRAPPER}"

# Check if source file exists
if [[ ! -f "${PYTHON_SOURCE}" ]]; then
  echo "Error: Source file not found: ${PYTHON_SOURCE}" >&2
  exit 1
fi

# Generate the wrapper script
cat > "${SHELL_WRAPPER}" <<'WRAPPER_HEADER'
#!/bin/bash
# Write Python validation script to /tmp/validate_drift.py
# This file is AUTO-GENERATED by scripts/generate_python_wrapper.sh
# DO NOT EDIT MANUALLY - Edit src/scripts/validate_drift.py instead

cat > /tmp/validate_drift.py <<'PYEOF'
WRAPPER_HEADER

# Append the Python script content
cat "${PYTHON_SOURCE}" >> "${SHELL_WRAPPER}"

# Append the closing heredoc and chmod
cat >> "${SHELL_WRAPPER}" <<'WRAPPER_FOOTER'
PYEOF

chmod +x /tmp/validate_drift.py
WRAPPER_FOOTER

chmod +x "${SHELL_WRAPPER}"

echo "Successfully generated ${SHELL_WRAPPER}"
echo ""
echo "Next steps:"
echo "  1. Review the generated file if needed"
echo "  2. Run: circleci orb pack src > orb.yml"

